apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb
  name: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - image: influxdb
        name: influxdb
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8086
        - name: admin
          containerPort: 8083
        volumeMounts:
          - name: docker-socket
            mountPath: /var/run/docker.sock
          - name: influxdb-pv
            mountPath: /var/lib/influxdb
      volumes:
        - name: docker-socket
          persistentVolumeClaim:
            claimName: docker-socket
        - name: influxdb-pv
          persistentVolumeClaim:
            claimName: influxdb-pv-claim