apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-socket
  labels:
    type: local
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 20Mi
  hostPath:
    path: "/var/run/docker.sock"
  storageClassName: docker-socket

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-socket
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 20Mi
  storageClassName: docker-socket