apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  annotations:
    metallb.universe.tf/address-pool: my-ip-space
    metallb.universe.tf/allow-shared-ip: commun-ip
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  type: LoadBalancer
  selector:
    app: grafana