apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
  annotations:
    metallb.universe.tf/address-pool: my-ip-space
    metallb.universe.tf/allow-shared-ip: commun-ip
spec:
  ports:
  - name: https
    port: 5000
    targetPort: 5000
  type: LoadBalancer
  selector:
    app: phpmyadmin