apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
  annotations:
    metallb.universe.tf/address-pool: my-ip-space
spec:
  ports:
	- name: phpmyadmin
	  port: 5000
	  targetPort: 5000
  type: LoadBalancer
  selector:
    app: phpmyadmin