apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress
  annotations:
    metallb.universe.tf/address-pool: my-ip-space
    metallb.universe.tf/allow-shared-ip: commun-ip
spec:
  ports:
  - name: https
    port: 5050
    targetPort: 5050
  type: LoadBalancer
  selector:
    app: wordpress