apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ftps
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - image: ftps
        name: ftps
        imagePullPolicy: Never
        ports:
          - name: https
            containerPort: 21
          - name: http
            containerPort: 20
          - name: pasv
            containerPort: 30000
      restartPolicy: Always