apiVersion: v1
kind: Service
metadata:
  labels:
    app: ftps
  name: ftps
  annotations:
    metallb.universe.tf/address-pool: my-ip-space
    metallb.universe.tf/allow-shared-ip: commun-ip
spec:
  ports:
    - name: https
      port: 21
      targetPort: 21
    - name: http
      port: 20
      targetPort: 20
    - name: pasv
      port: 30000
      targetPort: 30000
  type: LoadBalancer
  selector:
    app: ftps
