apiVersion: v1
kind: Service
metadata:
  labels:
    app: ftps
  name: ftps
  annotations:
    metallb.universe.tf/address-pool: my-ip-space
    metallb.universe.tf/allow-shared-ip: commun-ip
spec:
  ports:
  - name: https
    port: 21
    targetPort: 21
  type: LoadBalancer
  selector:
    app: ftps
